sudo: required
dist: trusty

language: php

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

services:
  - postgresql

before_install:
  - psql -c 'create database cms;' -U postgres

install:
  - composer install --prefer-source

script: phpunit

notifications:
  email: false
